name: Check files

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install pre-commit
              run: |
                  pip install black coverage mypy flake8 bandit pytest

            - name: Run Checks
              run: |
                  python -m black tests/ jo_seating_order/
                  python -m mypy tests/ jo_seating_order/
                  python -m bandit tests/ jo_seating_order/
                  python -m flake8 tests/ jo_seating_order/

            - name: Create Coverage report
              run: |
                  python -m coverage run -m pytest tests
                  python -m coverage report -m
